const SUPABASE_URL='https://hipzrtvrgjdeldfyudbc.supabase.co';
const SUPABASE_KEY='sb_publishable_NKHdv4Mza99fjiMBPk8C9A_bxcYmsmD';
const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const loginForm=$('login-form'),signupForm=$('signup-form'),resetRequestForm=$('reset-request-form'),resetVerifyForm=$('reset-verify-form'),newPasswordForm=$('new-password-form'),statusBox=$('status');
const loginSwitch=$('show-login'),signupSwitch=$('show-signup');
let resetEmail='';
function status(message,type=''){statusBox.textContent=message;statusBox.className='status '+type}
function markPinVerified(){try{sessionStorage.setItem('sadeeq_pin_verified','1')}catch{}}
function clearPinVerified(){try{sessionStorage.removeItem('sadeeq_pin_verified')}catch{}}
function hideForms(){loginForm.classList.add('hidden');signupForm.classList.add('hidden');resetRequestForm.classList.add('hidden');resetVerifyForm.classList.add('hidden');newPasswordForm.classList.add('hidden');$('pin-setup-panel').classList.add('hidden');$('pin-panel').classList.add('hidden');loginSwitch.classList.add('hidden');signupSwitch.classList.add('hidden')}
function showLogin(message=''){hideForms();loginForm.classList.remove('hidden');loginSwitch.classList.add('hidden');signupSwitch.classList.remove('hidden');$('title').textContent='Login';$('subtitle').textContent='This area is restricted to the system owner.';if(message)status(message,'ok')}
function showSignup(){hideForms();signupForm.classList.remove('hidden');loginSwitch.classList.remove('hidden');signupSwitch.classList.add('hidden');$('title').textContent='Initial Owner Signup';$('subtitle').textContent='This account can be created only once.'}
function showResetRequest(){hideForms();resetRequestForm.classList.remove('hidden');$('reset-email').value=$('email').value.trim();$('title').textContent='Forgot Password';$('subtitle').textContent='Enter the email registered to the owner account.';$('reset-email').focus();status('')}
function showResetVerify(){hideForms();resetVerifyForm.classList.remove('hidden');$('title').textContent='Verify Email';$('subtitle').textContent=`Enter the verification code sent to ${resetEmail}.`;$('reset-code').value='';$('reset-code').focus();status('Verification code sent to your email.','ok')}
function showNewPassword(){hideForms();newPasswordForm.classList.remove('hidden');$('title').textContent='Password Settings';$('subtitle').textContent='Email verified. Set your new owner password.';$('new-password').focus();status('Email verified successfully. Create your new password.','ok')}
function setSignupAvailability(available){signupSwitch.classList.toggle('hidden',!available);if(!available&&location.hash==='#signup')showLogin()}
async function ownerSignupAvailable(){const{data,error}=await client.rpc('sadeeq_owner_signup_available');if(error)return false;return data===true}
async function ownerHasPin(){const{data,error}=await client.rpc('owner_has_pin');if(error)throw error;return data===true}
async function openAfterAuth(message=''){try{const hasPin=await ownerHasPin();if(!hasPin){clearPinVerified();$('pin-setup-title').textContent='Set Owner PIN';$('pin-setup-panel').classList.remove('hidden');$('pin-panel').classList.add('hidden');loginForm.classList.add('hidden');signupForm.classList.add('hidden');resetRequestForm.classList.add('hidden');resetVerifyForm.classList.add('hidden');newPasswordForm.classList.add('hidden');loginSwitch.classList.add('hidden');signupSwitch.classList.add('hidden');$('title').textContent='Secure Owner Setup';$('subtitle').textContent=message||'Add a 6–12 digit PIN for the owner security gate.';status('Create your Owner PIN.','ok');$('setup-pin').focus();return}$('pin-panel').classList.remove('hidden');$('pin-setup-panel').classList.add('hidden');loginForm.classList.add('hidden');signupForm.classList.add('hidden');resetRequestForm.classList.add('hidden');resetVerifyForm.classList.add('hidden');newPasswordForm.classList.add('hidden');loginSwitch.classList.add('hidden');signupSwitch.classList.add('hidden');$('title').textContent='Owner Verification';$('subtitle').textContent='Enter your Owner PIN to continue.';status(message||'Password accepted. Enter your PIN.','ok');$('pin').focus()}catch(e){console.error(e);status('Security verification could not be loaded. Please try again.','error')}}
async function goOwnerGate(){const{data}=await client.auth.getSession();if(!data.session){clearPinVerified();showLogin();return}const{data:owner,error}=await client.from('sadeeq_owner_accounts').select('user_id').eq('user_id',data.session.user.id).maybeSingle();if(error||!owner){await client.auth.signOut();clearPinVerified();status('Owner account verification failed.','error');showLogin();return}await openAfterAuth()}
async function sendResetCode(){const email=$('reset-email').value.trim().toLowerCase();if(!email){status('Enter your owner email.','error');return false}resetEmail=email;status('Sending verification code...');const{error}=await client.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(error){console.error('Password reset OTP failed',error);status('Unable to send the verification code. Check the email and try again.','error');return false}showResetVerify();return true}
loginSwitch.onclick=showLogin;signupSwitch.onclick=showSignup;
$('forgot-password-btn').addEventListener('click',showResetRequest);
$('back-to-login-btn').addEventListener('click',()=>showLogin());
loginForm.addEventListener('submit',async e=>{e.preventDefault();const btn=loginForm.querySelector('button.primary');btn.disabled=true;clearPinVerified();status('Signing in...');const email=$('email').value.trim().toLowerCase();const password=$('password').value;const{data,error}=await client.auth.signInWithPassword({email,password});if(error||!data.session){console.error('Owner login failed',error);status('Login failed. Check your email and password, or use “Forgot Password?” to reset it.','error');btn.disabled=false;return}await openAfterAuth();btn.disabled=false});
resetRequestForm.addEventListener('submit',async e=>{e.preventDefault();const btn=resetRequestForm.querySelector('button.primary');btn.disabled=true;await sendResetCode();btn.disabled=false});
resetVerifyForm.addEventListener('submit',async e=>{e.preventDefault();const btn=resetVerifyForm.querySelector('button.primary');const code=$('reset-code').value.trim();if(!/^\d{6,8}$/.test(code)){status('Enter the verification code from your email.','error');return}btn.disabled=true;status('Verifying email...');const{data,error}=await client.auth.verifyOtp({email:resetEmail,token:code,type:'email'});if(error||!data.session){console.error('Password reset OTP verification failed',error);status('Verification failed. Check the code and try again.','error');btn.disabled=false;return}status('Email verified. Opening password settings...','ok');showNewPassword();btn.disabled=false});
$('resend-code-btn').addEventListener('click',async()=>{const btn=$('resend-code-btn');btn.disabled=true;await sendResetCode();btn.disabled=false});
newPasswordForm.addEventListener('submit',async e=>{e.preventDefault();const btn=newPasswordForm.querySelector('button.primary');const password=$('new-password').value,confirm=$('new-password-confirm').value;if(password.length<8){status('Password must be at least 8 characters.','error');return}if(password!==confirm){status('Passwords do not match.','error');return}btn.disabled=true;status('Saving new password...');const{error}=await client.auth.updateUser({password});if(error){console.error('Password update failed',error);status('Unable to update password. Please verify your email again.','error');btn.disabled=false;return}$('new-password').value='';$('new-password-confirm').value='';status('Password updated successfully. Continue to Owner Verification.','ok');await openAfterAuth('Password updated. Enter your Owner PIN to continue.');btn.disabled=false});
signupForm.addEventListener('submit',async e=>{e.preventDefault();const email=$('signup-email').value.trim().toLowerCase(),password=$('signup-password').value,confirm=$('signup-confirm').value;if(password.length<8){status('Password must be at least 8 characters.','error');return}if(password!==confirm){status('Passwords do not match.','error');return}const btn=signupForm.querySelector('button');btn.disabled=true;status('Creating the initial owner account...');if(!(await ownerSignupAvailable())){status('Initial Owner Signup is already closed.','error');setSignupAvailability(false);btn.disabled=false;return}const{data,error}=await client.auth.signUp({email,password});if(error){status(error.message,'error');btn.disabled=false;return}if(data.session){await openAfterAuth('Owner account created. Set your Owner PIN to finish setup.')}else{status('Account created. Confirm your email, then use Login.','ok');showLogin()}btn.disabled=false});
$('save-pin-btn').addEventListener('click',async()=>{const btn=$('save-pin-btn'),pin=$('setup-pin').value.trim(),confirmPin=$('setup-pin-confirm').value.trim();if(!/^[0-9]{6,12}$/.test(pin)){status('PIN must contain 6–12 digits.','error');return}if(pin!==confirmPin){status('PINs do not match.','error');return}btn.disabled=true;status('Saving Owner PIN...');const{data,error}=await client.rpc('owner_set_pin',{p_pin:pin});if(error||data!==true){status(error?.message==='INVALID_PIN'?'PIN must contain 6–12 digits.':'Unable to save Owner PIN.','error');btn.disabled=false;return}$('setup-pin').value='';$('setup-pin-confirm').value='';markPinVerified();status('Owner PIN saved. Opening console...','ok');window.location.replace('./dashboard.html')});
$('pin-btn').addEventListener('click',async()=>{const btn=$('pin-btn'),pin=$('pin').value.trim();if(!/^[0-9]{6,12}$/.test(pin)){status('Enter your 6–12 digit PIN.','error');btn.disabled=false;return}btn.disabled=true;status('Verifying PIN...');const{data,error}=await client.rpc('owner_verify_pin',{p_pin:pin});if(error||data!==true){status('Incorrect Owner PIN.','error');btn.disabled=false;$('pin').select();return}markPinVerified();$('pin').value='';status('Owner verified. Opening console...','ok');window.location.replace('./dashboard.html')});
$('forgot-pin-btn').addEventListener('click',async()=>{const password=prompt('Enter your owner password to reset the PIN:');if(password===null)return;if(!password){status('Password is required to reset the PIN.','error');return}const{data,error}=await client.auth.getUser();if(error||!data.user){status('Owner session expired.','error');return}const email=data.user.email||'';status('Verifying owner password...');const{data:login,error:loginError}=await client.auth.signInWithPassword({email,password});if(loginError||!login.session){status('Password verification failed.','error');return}clearPinVerified();$('pin').value='';$('pin-panel').classList.add('hidden');$('pin-setup-panel').classList.remove('hidden');$('pin-setup-title').textContent='Reset Owner PIN';$('title').textContent='Reset Owner PIN';$('subtitle').textContent='Password verified. Create a new 6–12 digit PIN.';status('Create your new Owner PIN.','ok');$('setup-pin').focus()});
(async()=>{const{data}=await client.auth.getSession();if(data.session){await goOwnerGate();return}const available=await ownerSignupAvailable();setSignupAvailability(available);if(location.hash==='#signup'&&available)showSignup();else showLogin()})();
