const SUPABASE_URL='https://hipzrtvrgjdeldfyudbc.supabase.co';
const SUPABASE_KEY='sb_publishable_NKHdv4Mza99fjiMBPk8C9A_bxcYmsmD';
const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const loginForm=$('login-form'),signupForm=$('signup-form'),statusBox=$('status');
const loginSwitch=$('show-login'),signupSwitch=$('show-signup');
function status(message,type=''){statusBox.textContent=message;statusBox.className='status '+type}
function showLogin(){loginForm.classList.remove('hidden');signupForm.classList.add('hidden');$('pin-setup-panel').classList.add('hidden');$('pin-panel').classList.add('hidden');loginSwitch.classList.add('hidden');signupSwitch.classList.remove('hidden');$('title').textContent='Login';$('subtitle').textContent='This area is restricted to the system owner.'}
function showSignup(){loginForm.classList.add('hidden');signupForm.classList.remove('hidden');$('pin-setup-panel').classList.add('hidden');$('pin-panel').classList.add('hidden');loginSwitch.classList.remove('hidden');signupSwitch.classList.add('hidden');$('title').textContent='Initial Owner Signup';$('subtitle').textContent='This account can be created only once.'}
function setSignupAvailability(available){signupSwitch.classList.toggle('hidden',!available);if(!available&&location.hash==='#signup')showLogin()}
async function ownerSignupAvailable(){const{data,error}=await client.rpc('sadeeq_owner_signup_available');if(error)return false;return data===true}
async function ownerHasPin(){const{data,error}=await client.rpc('owner_has_pin');if(error)throw error;return data===true}
async function openAfterAuth(message=''){try{const hasPin=await ownerHasPin();if(!hasPin){$('pin-setup-title').textContent='Set Owner PIN';$('pin-setup-panel').classList.remove('hidden');$('pin-panel').classList.add('hidden');loginForm.classList.add('hidden');signupForm.classList.add('hidden');loginSwitch.classList.add('hidden');signupSwitch.classList.add('hidden');$('title').textContent='Secure Owner Setup';$('subtitle').textContent=message||'Add a 6–12 digit PIN for the second owner security gate.';status('Create your Owner PIN.','ok');return}$('pin-panel').classList.remove('hidden');$('pin-setup-panel').classList.add('hidden');loginForm.classList.add('hidden');signupForm.classList.add('hidden');loginSwitch.classList.add('hidden');signupSwitch.classList.add('hidden');$('title').textContent='Owner Verification';$('subtitle').textContent='Enter your Owner PIN to continue.';status('Password accepted. Enter your PIN.','ok');$('pin').focus()}catch(e){console.error(e);status('Security verification could not be loaded. Please try again.','error')}}
async function goOwnerGate(){const{data}=await client.auth.getSession();if(!data.session){showLogin();return}const{data:owner}=await client.from('sadeeq_owner_accounts').select('user_id').eq('user_id',data.session.user.id).maybeSingle();if(!owner){await client.auth.signOut();status('Owner account verification failed.','error');showLogin();return}await openAfterAuth()}
loginSwitch.onclick=showLogin;
signupSwitch.onclick=showSignup;
loginForm.addEventListener('submit',async e=>{e.preventDefault();const btn=loginForm.querySelector('button');btn.disabled=true;status('Signing in...');const email=$('email').value.trim();const{data,error}=await client.auth.signInWithPassword({email,password:$('password').value});if(error||!data.session){status('Login failed. Check your email and password.','error');btn.disabled=false;return}await openAfterAuth();btn.disabled=false});
signupForm.addEventListener('submit',async e=>{e.preventDefault();const email=$('signup-email').value.trim();const password=$('signup-password').value;const confirm=$('signup-confirm').value;if(password.length<8){status('Password must be at least 8 characters.','error');return}if(password!==confirm){status('Passwords do not match.','error');return}const btn=signupForm.querySelector('button');btn.disabled=true;status('Creating the initial owner account...');if(!(await ownerSignupAvailable())){status('Initial Owner Signup is already closed.','error');setSignupAvailability(false);btn.disabled=false;return}const{data,error}=await client.auth.signUp({email,password});if(error){status(error.message,'error');btn.disabled=false;return}if(data.session){await openAfterAuth('Owner account created. Set your Owner PIN to finish setup.')}else{status('Account created. Confirm your email, then use Login.','ok');showLogin()}btn.disabled=false});
$('save-pin-btn').addEventListener('click',async()=>{const btn=$('save-pin-btn'),pin=$('setup-pin').value.trim(),confirmPin=$('setup-pin-confirm').value.trim();if(!/^[0-9]{6,12}$/.test(pin)){status('PIN must contain 6–12 digits.','error');return}if(pin!==confirmPin){status('PINs do not match.','error');return}btn.disabled=true;status('Saving Owner PIN...');const{data,error}=await client.rpc('owner_set_pin',{p_pin:pin});if(error||data!==true){status(error?.message==='INVALID_PIN'?'PIN must contain 6–12 digits.':'Unable to save Owner PIN.','error');btn.disabled=false;return}pin.value='';$('setup-pin').value='';$('setup-pin-confirm').value='';status('Owner PIN saved. Opening console...','ok');window.location.replace('./dashboard.html');});
$('pin-btn').addEventListener('click',async()=>{const btn=$('pin-btn'),pin=$('pin').value.trim();if(!/^[0-9]{6,12}$/.test(pin)){status('Enter your 6–12 digit PIN.','error');return}btn.disabled=true;status('Verifying PIN...');const{data,error}=await client.rpc('owner_verify_pin',{p_pin:pin});if(error||data!==true){status('Incorrect Owner PIN.','error');btn.disabled=false;$('pin').select();return}$('pin').value='';status('Owner verified. Opening console...','ok');window.location.replace('./dashboard.html')});
$('forgot-pin-btn').addEventListener('click',async()=>{const password=prompt('Enter your owner password to reset the PIN:');if(password===null)return;if(!password){status('Password is required to reset the PIN.','error');return}const{data,error}=await client.auth.getUser();if(error||!data.user){status('Owner session expired.','error');return}const email=data.user.email||'';status('Verifying owner password...');const{data:login,error:loginError}=await client.auth.signInWithPassword({email,password});if(loginError||!login.session){status('Password verification failed.','error');return}$('pin').value='';$('pin-panel').classList.add('hidden');$('pin-setup-panel').classList.remove('hidden');$('pin-setup-title').textContent='Reset Owner PIN';$('title').textContent='Reset Owner PIN';$('subtitle').textContent='Password verified. Create a new 6–12 digit PIN.';status('Create your new Owner PIN.','ok')});
(async()=>{const available=await ownerSignupAvailable();setSignupAvailability(available);const{data}=await client.auth.getSession();if(data.session){await goOwnerGate();return}if(location.hash==='#signup'&&available)showSignup();else showLogin()})();
